apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 4
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
        role: database
      name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
            - containerPort: 28017
          command:
            - mongod
            - "--smallfiles"
