apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 4
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
        role: database
      name: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
