apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    name: shop
  template:
    metadata:
      labels:
        name: shop
        role: frontend
      name: shop
    spec:
      containers:
        - name: shop
          image: zutherb/monolithic-shop
          ports:
            - containerPort: 8080
